# Run tests on every push
name: Test

on: [push]

jobs:
  test:
    name: Testing
    # Test on ubuntu latest for best variance
    runs-on: ubuntu-latest
    # Make tests on 4 different Versions of Python
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]

    # We need to build sqlite3 from source, as the default version produces an error
    steps:
      - uses: actions/checkout@v2

      - name: pull working sqlite version
        run: |
          wget https://sqlite.org/2022/sqlite-autoconf-3380500.tar.gz
          tar -xvf sqlite-autoconf-3380500.tar.gz
      - name: configure sqlite for build process
        run: ./configure
        working-directory: sqlite-autoconf-3380500

      - name: build the sqlite version
        run: make
        working-directory: sqlite-autoconf-3380500

      - name: install the sqlite version
        run: sudo make install
        working-directory: sqlite-autoconf-3380500

      - name: set path for the sqlite version
        run: export PATH="/usr/local/lib:$PATH"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Install all dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest mypy pycodestyle pydocstyle
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Linters/Code Analysers
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

      - name: Analyse with mypy
        run: mypy .

      - name: Analyse with pycodestyle
        run: python -m pycodestyle --select E,W . --max-line-length=120

      - name: Analyse with pydocstyle
        run: python -m pydocstyle .

      # Run pytest as last action
      - name: Test with pytest
        run: |
          pytest .
        env:
          LD_LIBRARY_PATH: /usr/local/lib
