# Run tests on every push
name: Test

on: [push]

jobs:
  test:
    name: Testing
    # Test on ubuntu latest for best variance
    runs-on: ubuntu-latest
    # Test on 4 different Versions of Python
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]

    # We need to build sqlite3 from source, as the default version produces an error
    steps:
      - uses: actions/checkout@v2

      - name: pull working sqlite version
        run: |
          wget https://sqlite.org/2022/sqlite-autoconf-3380500.tar.gz
          tar -xvf sqlite-autoconf-3380500.tar.gz
      - name: configure sqlite for build process
        run: ./configure
        working-directory: sqlite-autoconf-3380500

      - name: build the sqlite version
        run: make
        working-directory: sqlite-autoconf-3380500

      - name: install the sqlite version
        run: sudo make install
        working-directory: sqlite-autoconf-3380500

      - name: set path for the sqlite version
        run: export PATH="/usr/local/lib:$PATH"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Install all dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest mypy pycodestyle pydocstyle
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Linters/Code Analysers
      - name: Lint with flake8
        run: |
          flake8 cli_habit.py --max-line-length=120
          flake8 db.py --max-line-length=120
          flake8 habit.py --max-line-length=120
          flake8 main.py --max-line-length=120
          flake8 sample_data.py --max-line-length=120
          flake8 test_cli.py --max-line-length=120
          flake8 test_db.py --max-line-length=120
          flake8 test_project.py --max-line-length=120
          flake8 ./cli/__init__.py --max-line-length=120
          flake8 . --count --show-source --statistics --max-line-length=120


      - name: Analyse with mypy
        run: |
          python -m mypy cli_habit.py
          python -m mypy db.py
          python -m mypy habit.py
          python -m mypy main.py
          python -m mypy sample_data.py
          python -m mypy test_cli.py
          python -m mypy test_db.py
          python -m mypy test_project.py
          python -m mypy ./cli/__init__.py
          python -m mypy .

      - name: Analyse with pycodestyle
        run: |
          python -m pycodestyle --select E,W cli_habit.py --max-line-length=120
          python -m pycodestyle --select E,W db.py --max-line-length=120
          python -m pycodestyle --select E,W habit.py --max-line-length=120
          python -m pycodestyle --select E,W main.py --max-line-length=120
          python -m pycodestyle --select E,W sample_data.py --max-line-length=120
          python -m pycodestyle --select E,W test_cli.py --max-line-length=120
          python -m pycodestyle --select E,W test_db.py --max-line-length=120
          python -m pycodestyle --select E,W test_project.py --max-line-length=120
          python -m pycodestyle --select E,W ./cli/__init__.py --max-line-length=120
          python -m pycodestyle --select E,W . --max-line-length=120

      - name: Analyse with pydocstyle
        run: | 
          python -m pydocstyle cli_habit.py
          python -m pydocstyle db.py
          python -m pydocstyle habit.py
          python -m pydocstyle main.py
          python -m pydocstyle sample_data.py
          python -m pydocstyle test_cli.py
          python -m pydocstyle test_db.py
          python -m pydocstyle test_project.py
          python -m pydocstyle ./cli/__init__.py
          python -m pydocstyle .

      # Run pytest as last action
      - name: Test with pytest
        run: |
          pytest .
        env:
          LD_LIBRARY_PATH: /usr/local/lib
